VARIABLE_LABELS_ORIG = {
    "tenure": "Tenure on survey",
    "weight": "Sampling weight",
    "Q1": "Financially better/worse off than 12 months ago",
    "Q2": "Financially better/worse off 12 months from now",
    "Q3": "Prob to move house",
    "Q4new": "Prob unemployment higher in 12 months",
    "Q5new": "Prob interest rates higher in 12 months",
    "Q6new": "Prob stocks higher in 12 months",
    "Q8v2": "Inflation/deflation over next 12 months?",
    "Q8v2part2": "Rate of inflation/deflation over next 12 months",
    "Q9": "Prob of different inflation rates over the next 12 months?",
    "Q9bv2": "Will there be inflation or deflation 24 to 36 months from now?",
    "Q9bv2part2": "Rate of inflation/deflation 24 to 36 months from now",
    "Q9c": "Prob of different inflation rates 24 to 36 months from now",
    "Q1a": "Will there be inflation or deflation 48 to 60 months from now?",
    "Q1apart2": "Rate of inflation/deflation 48 to 60 months from now",
    "Q9new2": "Prob of different inflation rates 48 to 60 months from now",
    "Q10": "Current employment situation",
    "Q11": "Number of jobs",
    "Q12new": "Do you work for someone else or are you self-employed?",
    "ES1": "What type of self-employed work do you do?",
    "ES2": "How many paid employees does your business have?",
    "ES3new": "Chance your business will have more workers next year?",
    "ES4": "How many hours per week have you worked recently?",
    "ES5": "How many hours per week do you expect to work?",
    "Q13new": "Prob to lose job over next 12 months",
    "Q14new": "Prob to leave job over next 12 months",
    "Q15": "Looking for job?",
    "Q16": "How long have you been unemployed?",
    "Q17new": "Prob to accept job over next 12 months",
    "Q18new": "Prob to accept job over next 3 months",
    "Q19": "How long have you been out of work?",
    "Q20new": "Prob to start looking for a job within 12 months",
    "Q21new": "Prob to start looking for a job within 3 months?",
    "Q22new": "Prob to accept job over next 3 months if lost job",
    "Q23v2": "Earnings increase/decrease",
    "Q23v2part2": "Percent change in earnings",
    "Q24": "Chance your job earnings will change by a certain percent?",
    "Q25v2": "HH income increase/decrease",
    "Q25v2part2": "Percent change in HH income",
    "Q26v2": "HH spending increase/decrease",
    "Q26v2part2": "Percent change in HH spending",
    "Q27v2": "Taxes increase/decrease",
    "Q27v2part2": "Percent change in taxes",
    "Q28": "Credit conditions vs 12 months ago",
    "Q29": "Credit conditions in 12 months",
    "Q30new": "Prob to miss debt payment over 3 months?",
    "Q31v2": "House prices increase/decrease",
    "Q31v2part2": "Percent change in house prices",
    "C1": "Chance home prices will change by a certain percent?",
    "C2": "House prices incr/decr 24 to 36 months from now",
    "C2part2": "% change in house prices 24 to 36 months from now",
    "C3": "Gov debt increase/decrease",
    "C3part2": "Percent change in government debt",
    "C4info": "How will prices of items change in twelve months?",
    "QNUM1": "A $300 sofa is half price. What is the cost?",
    "QNUM2": "$200 savings earns 10% yearly. Total after two years?",
    "QNUM3": "1% chance of winning. How many winners out of 1000?",
    "QNUM5": "10% get a disease. How many out of 1,000?",
    "QNUM6": "Infection chance 0.0005. How many infected out of 10,000?",
    "QNUM8": "Interest 1%, inflation 2%. Can you buy more/less?",
    "QNUM9": "Single stock safer than MF",
    "Q32": "Initial age",
    "Q33": "Gender",
    "Q34": "Hispanic/Latino?",
    "Q35": "Race",
    "Q36": "Education",
    "Q37": "How long in current job?",
    "Q38": "Married/living with partner?",
    "HH2": "Partner's employment status",
    "Q39": "ZIP code",
    "Q40": "State of residence",
    "Q41": "Years lived in current residence",
    "Q42": "Years lived in current state?",
    "Q43": "Own/rent residence?",
    "Q43a": "In whose name is your home owned or rented?",
    "Q44": "Own any other homes?",
    "Q45new": "How many people live in your household besides you?",
    "Q45b": "Self-reported health",
    "Q46": "Financial decision making",
    "QRA1": "Willingness to take financial risks?",
    "QRA2": "Willingness to take risks in daily activities?",
    "Q47": "Total HH income during past 12 months",
    "D1": "HH unchaged from last survey",
    "D2new": "How many people currently live in your household?",
    "D3": "Moved since last survey?",
    "D4": "What is your current ZIP code?",
    "D5": "In which state do you currently live?",
    "DSAME": "Same job as last survey?",
    "dQ38": "Married/living with partner?",
    "dHH2": "Partner's employment status",
    "D6": "Total HH income during past 12 months",
    "Q48": "How interesting did you find this survey?",
    "Q49": "Do you have any other comments about the survey?"
}

VARIABLE_LABELS = {
    "tenure": "Tenure on survey",
    "weight": "Sampling weight",
    "financial_past_12m": "Financially better/worse off than 12 months ago",
    "financial_12m": "Financially better/worse off 12 months from now",
    "prob_move_house": "Prob to move house",
    "prob_unrate_up": "Prob unemployment higher in 12 months",
    "prob_irate_up": "Prob interest rates higher in 12 months",
    "prob_stocks_up": "Prob stocks higher in 12 months",
    "infl_1y": "Rate of inflation/deflation over next 12 months",
    "infl_3y": "Rate of inflation/deflation 24 to 36 months from now",
    "infl_5y": "Rate of inflation/deflation 48 to 60 months from now",
    "working": "Currently working?",
    "num_jobs": "Number of jobs",
    "self_employed": "Self-employed?",
    "prob_lose_job": "Prob to lose job over next 12 months",
    "prob_leave_job": "Prob to leave job over next 12 months",
    "looking_for_job": "Looking for job?",
    "prob_accept_job_12m": "Prob to accept job over next 12 months",
    "prob_accept_job_3m": "Prob to accept job over next 3 months",
    "jobless_length": "How long unempl/out of work?",
    "prob_search_job_12m": "Prob to start looking for a job within 12 months",
    "prob_search_job_3m": "Prob to start looking for a job within 3 months?",
    "earnings_change": "Percent change in earnings",
    "hh_income_change": "Percent change in HH income",
    "hh_spending_change": "Percent change in HH spending",
    "taxes_change": "Percent change in taxes",
    "credit_cond_past12m": "Credit conditions vs 12 months ago",
    "credit_cond_12m": "Credit conditions in 12 months",
    "prob_miss_paym_3m": "Prob to miss debt payment over 3 months?",
    "house_price_change": "Percent change in house prices",
    "house_price_change_3y": "Percent change in house prices 24 to 36 months from now",
    "govt_debt_change": "Percent change in government debt",
    "num_lit_q1": "A $300 sofa is half price. What is the cost?",
    "num_lit_q1_correct": "Num Q1 correct",
    "num_lit_q2": "$200 savings earns 10% yearly. Total after two years?",
    "num_lit_q2_correct": "Num Q2 correct",
    "num_lit_q3": "1% chance of winning. How many winners out of 1000?",
    "num_lit_q3_correct": "Num Q3 correct",
    "num_lit_q5": "10% get a disease. How many out of 1,000?",
    "num_lit_q5_correct": "Num Q5 correct",
    "num_lit_q6": "Infection chance 0.0005. How many infected out of 10,000?",
    "num_lit_q6_correct": "Num Q6 correct",
    "num_lit_q8": "Interest 1%, inflation 2%. Can you buy more/less?",
    "num_lit_q8_correct": "Num Q8 correct",
    "num_lit_q9": "Single stock safer than MF",
    "num_lit_q9_correct": "Num Q9 correct",
    "age_init": "Initial age",
    "female": "Female?",
    "hispanic": "Hispanic/Latino?",
    "black": "Black/AA?",
    "educ": "Education",
    "college": "College degree?",
    "owner": "Owns primary residence?",
    "num_kids": "Number of kids",
    "health": "Self-reported health",
    "take_fin_risk": "Willingness to take financial risks?",
    "hh_income": "Total HH income during past 12 months",
    "hh_changed": "HH unchaged from last survey",
    "same_employer": "Same job as last survey?",
    "couple": "Married/living with partner?",
    "spouse_working": "Spouse/partner currently working?"
}
