

VARIABLE_LABELS_ORIG = {
    "Q1": "Financially better or worse off than 12 months ago",
    "Q2": "Financiually better or worse off 12 months from now",
    "Q3": "Prob to move house",
    "Q4new": "Prob unemployment will be higher in 12 months",
    "Q5new": "Prob interest rates will be higher in 12 months",
    "Q6new": "Prob stocks will be higher in 12 months",
    "Q8v2": "Will there be inflation or deflation over the next 12 months?",
    "Q8v2part2": "Rate of inflation/deflation over next 12 months",
    "Q9": "Prob of different inflation rates over the next 12 months?",
    "Q9bv2": "Will there be inflation or deflation 24 to 36 months from now?",
    "Q9bv2part2": "Rate of inflation/deflation 24 to 36 months from now",
    "Q9c": "Prob of different inflation rates 24 to 36 months from now",
    "Q1A": "Will there be inflation or deflation 48 to 60 months from now?",
    "Q1A_part2": "Rate of inflation/deflation 48 to 60 months from now",
    "Q9new2": "Prob of different inflation rates 48 to 60 months from now",
    "Q10": "Current employment situation",
    "Q11": "Number of jobs",
    "Q12new": "Do you work for someone else or are you self-employed?",
    "ES1": "What type of self-employed work do you do?",
    "ES2": "How many paid employees does your business have?",
    "ES3new": "Chance your business will have more workers next year?",
    "ES4": "How many hours per week have you worked recently?",
    "ES5": "How many hours per week do you expect to work?",
    "Q13new": "Prob to lose job over next 12 months",
    "Q14new": "Prob to leave job over next 12 months",
    "Q15": "Looking for job?",
    "Q16": "How long have you been unemployed?",
    "Q17new": "Prob to accept job over next 12 months",
    "Q18new": "Prob to accept job over next 3 months",
    "Q19": "How long have you been out of work?",
    "Q20new": "Prob to start looking for a job within 12 months",
    "Q21new": "Prob to start looking for a job within 3 months?",
    "Q22new": "Prob to accept job over next 3 months if lost job",
    "Q23v2": "Earnings increase/decrease",
    "Q23v2part2": "Percent change in earnings",
    "Q24": "Chance your job earnings will change by a certain percent?",
    "Q25v2": "HH income increase/decrease",
    "Q25v2part2": "Percent change in HH income",
    "Q26v2": "HH spending increase/decrease",
    "Q26v2part2": "Percent change in HH spending",
    "Q27v2": "Taxes increase/decrease",
    "Q27v2part2": "Percent change in taxes",
    "Q28": "Credit conditions vs 12 months ago",
    "Q29": "Credit conditions in 12 months",
    "Q30new": "Prob to miss debt payment over 3 months?",
    "Q31v2": "House prices increase/decrease",
    "Q31v2part2": "Percent change in house prices",
    "C1": "Chance home prices will change by a certain percent?",
    "C2": "House prices incr/decr 24 to 36 months from now",
    "C2part2": "% change in house prices 24 to 36 months from now",
    "C3": "Gov debt increase/decrease",
    "C3part2": "Percent change in government debt",
    "C4info": "How will prices of items change in twelve months?",
    "QNUM1": "A $300 sofa is half price. What is the cost?",
    "QNUM2": "$200 savings earns 10% yearly. Total after two years?",
    "QNUM3": "1% chance of winning. How many winners out of 1000?",
    "QNUM5": "10% get a disease. How many out of 1,000?",
    "QNUM6": "Infection chance 0.0005. How many infected out of 10,000?",
    "QNUM8": "Interest 1%, inflation 2%. Can you buy more/less?",
    "QNUM9": "Single stock safer than MF",
    "Q32": "Initial age",
    "Q33": "Gender",
    "Q34": "Hispanic/Latino?",
    "Q35": "Race",
    "Q36": "Education",
    "Q37": "How long in current job?",
    "Q38": "Married/living with partner?",
    "HH2": "Partner's employment status",
    "Q39": "ZIP code",
    "Q40": "State of residence",
    "Q41": "Years lived in current residence",
    "Q42": "Years lived in current state?",
    "Q43": "Own/rent residence?",
    "Q43a": "In whose name is your home owned or rented?",
    "Q44": "Own any other homes?",
    "Q45new": "How many people live in your household besides you?",
    "Q45b": "How would you rate your health?",
    "Q46": "How are financial decisions made in your household?",
    "QRA1": "How willing are you to take financial risks?",
    "QRA2": "How willing are you to take risks in daily activities?",
    "Q47": "What was your total household income last year?",
    "D1": "Is your household the same as your last survey?",
    "D2new": "How many people currently live in your household?",
    "D3": "Have you moved since the last survey?",
    "D4": "What is your current ZIP code?",
    "D5": "In which state do you currently live?",
    "DSAME": "Are you in the same job as last survey?",
    "dQ38": "Are you married or living with a partner?",
    "dHH2": "What is your spouse/partner's current employment situation?",
    "D6": "What was your total household income last year?",
    "Q48": "How interesting did you find this survey?",
    "Q49": "Do you have any other comments about the survey?"
}