"""Stable dtype column groups for processed SCE outputs."""

# These variables contain small response-category, count, or panel-position codes.
# The pooled set is safe for both outputs because casting ignores absent columns.
NULLABLE_INT8_COLUMNS = frozenset(
    {
        "tenure",
        "Q1",
        "Q2",
        "Q11",
        "Q12new",
        "Q15",
        "Q23v2",
        "Q25v2",
        "Q26v2",
        "Q27v2",
        "Q28",
        "Q29",
        "Q31v2",
        "C2",
        "C3",
        "QNUM8",
        "QNUM9",
        "Q32",
        "age_init",
        "Q33",
        "Q34",
        "black",
        "Q36",
        "Q37",
        "Q38",
        "Q43",
        "Q44",
        "Q45b",
        "Q46",
        "QRA1",
        "QRA2",
        "Q47",
        "D1",
        "D3",
        "DSAME",
        "financial_past_12m",
        "financial_12m",
        "working",
        "num_jobs",
        "self_employed",
        "looking_for_job",
        "credit_cond_past_12m",
        "credit_cond_12m",
        "num_lit_q1_correct",
        "num_lit_q2_correct",
        "num_lit_q3_correct",
        "num_lit_q5_correct",
        "num_lit_q6_correct",
        "num_lit_q8",
        "num_lit_q8_correct",
        "num_lit_q9",
        "num_lit_q9_correct",
        "female",
        "hispanic",
        "college",
        "educ",
        "owner",
        "health",
        "take_fin_risk",
        "num_kids",
        "same_employer",
        "couple",
        "hh_changed",
        "spouse_working",
        "hh_inc_bin",
    }
    | {f"Q10_{i}" for i in range(1, 11)}
    | {f"Q35_{i}" for i in range(1, 7)}
    | {f"Q45new_{i}" for i in range(1, 10)}
    | {f"HH2_{i}" for i in range(1, 12)}
)
